import re
import unicodedata


def normalizar_palabra(texto):
    texto = str(texto or "").strip().lower()
    texto = unicodedata.normalize("NFD", texto)
    texto = "".join(letra for letra in texto if unicodedata.category(letra) != "Mn")
    return texto


DICCIONARIO_HEBREO = [
    {
        "palabra": "Jehova",
        "hebreo": "יהוה",
        "transliteracion": "YHWH / Yahweh",
        "significado": "El que es; el Eterno; nombre del Senor.",
        "descripcion": "Nombre sagrado de Dios en el texto hebreo. En Reina-Valera suele aparecer como Jehova.",
        "aliases": ["Jehova", "Jehová", "Jah", "Yahweh", "Yahveh"],
    },
    {
        "palabra": "Aleluya",
        "hebreo": "הללו־יה",
        "transliteracion": "Hallelu-Yah",
        "significado": "Alabad a Jah / alabad al Senor.",
        "descripcion": "Expresion hebrea de adoracion y alabanza.",
        "aliases": ["Aleluya", "Alleluya"],
    },
    {
        "palabra": "Amen",
        "hebreo": "אמן",
        "transliteracion": "Amen",
        "significado": "Verdad; firme; asi sea.",
        "descripcion": "Expresion de confirmacion, fidelidad y acuerdo delante de Dios.",
        "aliases": ["Amen", "Amén"],
    },
    {
        "palabra": "Hosanna",
        "hebreo": "הושיעה נא",
        "transliteracion": "Hoshia na",
        "significado": "Salva ahora, te rogamos.",
        "descripcion": "Clamor de salvacion y alabanza usado en la entrada triunfal.",
        "aliases": ["Hosanna", "Hosana"],
    },
    {
        "palabra": "Rabí",
        "hebreo": "רבי",
        "transliteracion": "Rabbi",
        "significado": "Mi maestro.",
        "descripcion": "Titulo de respeto para un maestro espiritual.",
        "aliases": ["Rabi", "Rabí", "Rabboni", "Raboni"],
    },
    {
        "palabra": "Mesias",
        "hebreo": "משיח",
        "transliteracion": "Mashiaj",
        "significado": "Ungido.",
        "descripcion": "Titulo hebreo del Ungido prometido por Dios.",
        "aliases": ["Mesias", "Mesías", "Mashiaj", "Mesiás"],
    },
    {
        "palabra": "Emanuel",
        "hebreo": "עמנו אל",
        "transliteracion": "Immanu El",
        "significado": "Dios con nosotros.",
        "descripcion": "Nombre profetico asociado al nacimiento del Mesias.",
        "aliases": ["Emanuel", "Emmanuel"],
    },
    {
        "palabra": "Sion",
        "hebreo": "ציון",
        "transliteracion": "Tsiyyon",
        "significado": "Sion; monte o ciudad escogida.",
        "descripcion": "Nombre biblico vinculado a Jerusalen, al pueblo de Dios y a su monte santo.",
        "aliases": ["Sion", "Sión"],
    },
    {
        "palabra": "Eden",
        "hebreo": "עדן",
        "transliteracion": "Eden",
        "significado": "Delicia; placer; lugar de deleite.",
        "descripcion": "Nombre del jardin donde Dios puso al hombre al principio.",
        "aliases": ["Eden", "Edén"],
    },
    {
        "palabra": "Satanas",
        "hebreo": "שטן",
        "transliteracion": "Satan",
        "significado": "Adversario; acusador.",
        "descripcion": "Nombre usado para el enemigo y acusador.",
        "aliases": ["Satanas", "Satanás", "Satan"],
    },
    {
        "palabra": "Querubin",
        "hebreo": "כרוב",
        "transliteracion": "Keruv",
        "significado": "Ser celestial asociado a la presencia y gloria de Dios.",
        "descripcion": "En plural, querubines. Aparecen guardando lugares santos y ligados al arca.",
        "aliases": ["Querubin", "Querubín", "Querubines"],
    },
    {
        "palabra": "Serafin",
        "hebreo": "שרף",
        "transliteracion": "Saraf",
        "significado": "Ardiente.",
        "descripcion": "Ser celestial mencionado en la vision de Isaias.",
        "aliases": ["Serafin", "Serafín", "Serafines"],
    },
    {
        "palabra": "Abba",
        "hebreo": "אבא",
        "transliteracion": "Abba",
        "significado": "Padre.",
        "descripcion": "Termino de cercania filial usado en oracion a Dios.",
        "aliases": ["Abba"],
    },
    {
        "palabra": "Maranata",
        "hebreo": "מרנא תא",
        "transliteracion": "Maranatha",
        "significado": "El Senor viene / ven, Senor.",
        "descripcion": "Expresion aramea usada por la iglesia primitiva.",
        "aliases": ["Maranata", "Maranatha"],
    },
    {
        "palabra": "Golgota",
        "hebreo": "גלגלתא",
        "transliteracion": "Golgotha",
        "significado": "Lugar de la calavera.",
        "descripcion": "Nombre del lugar donde fue crucificado Jesus.",
        "aliases": ["Golgota", "Gólgota"],
    },
    {
        "palabra": "Elí",
        "hebreo": "אלי",
        "transliteracion": "Eli",
        "significado": "Dios mio.",
        "descripcion": "Parte del clamor: Eli, Eli, lama sabactani.",
        "aliases": ["Eli", "Elí", "Eloi", "Eloí"],
    },
    {
        "palabra": "Sabactani",
        "hebreo": "שבקתני",
        "transliteracion": "Shabaqtani",
        "significado": "Me has desamparado.",
        "descripcion": "Parte del clamor de Jesus en la cruz.",
        "aliases": ["Sabactani", "Sabactaní"],
    },
]

DICCIONARIO_HEBREO.extend(
    [
        {
            "palabra": "Majano",
            "hebreo": "\u05d2\u05dc",
            "transliteracion": "Gal",
            "significado": "Monton, pila o monticulo de piedras.",
            "descripcion": "En el contexto biblico puede referirse a un monton levantado como senal o testimonio.",
            "aliases": ["Majano", "Majanos"],
        },
        {
            "palabra": "Galaad",
            "hebreo": "\u05d2\u05dc\u05e2\u05d3",
            "transliteracion": "Gilad / Gal-ed",
            "significado": "Majano o monton de testimonio.",
            "descripcion": "Nombre vinculado al testimonio levantado con piedras; tambien region al oriente del Jordan.",
            "aliases": ["Galaad", "Galeed", "Galaadita", "Galaaditas"],
        },
        {
            "palabra": "Elohim",
            "hebreo": "\u05d0\u05dc\u05d4\u05d9\u05dd",
            "transliteracion": "Elohim",
            "significado": "Dios; Dios poderoso.",
            "descripcion": "Titulo hebreo usado para Dios, especialmente en el relato de la creacion.",
            "aliases": ["Elohim"],
        },
        {
            "palabra": "Adonai",
            "hebreo": "\u05d0\u05d3\u05e0\u05d9",
            "transliteracion": "Adonai",
            "significado": "Senor; mi Senor.",
            "descripcion": "Titulo reverente usado para dirigirse a Dios.",
            "aliases": ["Adonai"],
        },
        {
            "palabra": "Shaddai",
            "hebreo": "\u05e9\u05d3\u05d9",
            "transliteracion": "Shaddai",
            "significado": "Todopoderoso.",
            "descripcion": "Titulo divino conocido en la expresion El Shaddai.",
            "aliases": ["Shaddai", "Sadai"],
        },
        {
            "palabra": "Shalom",
            "hebreo": "\u05e9\u05dc\u05d5\u05dd",
            "transliteracion": "Shalom",
            "significado": "Paz, plenitud, bienestar.",
            "descripcion": "Palabra hebrea de paz integral y armonia.",
            "aliases": ["Shalom", "Salem"],
        },
        {
            "palabra": "Sheol",
            "hebreo": "\u05e9\u05d0\u05d5\u05dc",
            "transliteracion": "Sheol",
            "significado": "Lugar de los muertos; sepulcro.",
            "descripcion": "Termino hebreo usado para el ambito de la muerte.",
            "aliases": ["Sheol", "Seol"],
        },
        {
            "palabra": "Torah",
            "hebreo": "\u05ea\u05d5\u05e8\u05d4",
            "transliteracion": "Torah",
            "significado": "Ley, instruccion, ensenanza.",
            "descripcion": "Instruccion divina; tambien nombre del conjunto de los cinco libros de Moises.",
            "aliases": ["Torah", "Tora"],
        },
        {
            "palabra": "Pesaj",
            "hebreo": "\u05e4\u05e1\u05d7",
            "transliteracion": "Pesaj",
            "significado": "Pascua; pasar por alto.",
            "descripcion": "Fiesta que recuerda la liberacion de Israel de Egipto.",
            "aliases": ["Pesaj", "Pascua"],
        },
        {
            "palabra": "Sabat",
            "hebreo": "\u05e9\u05d1\u05ea",
            "transliteracion": "Shabbat",
            "significado": "Reposo; cesar.",
            "descripcion": "Dia de descanso consagrado a Dios.",
            "aliases": ["Sabat", "Sabado", "Shabbat"],
        },
        {
            "palabra": "Jubileo",
            "hebreo": "\u05d9\u05d5\u05d1\u05dc",
            "transliteracion": "Yovel",
            "significado": "Jubileo; toque o cuerno de carnero.",
            "descripcion": "Ano especial de liberacion y restitucion en la ley de Moises.",
            "aliases": ["Jubileo", "Yovel"],
        },
        {
            "palabra": "Manna",
            "hebreo": "\u05de\u05df",
            "transliteracion": "Man",
            "significado": "¿Que es esto?",
            "descripcion": "Alimento dado por Dios a Israel en el desierto.",
            "aliases": ["Mana", "Maná", "Manna"],
        },
        {
            "palabra": "Efod",
            "hebreo": "\u05d0\u05e4\u05d5\u05d3",
            "transliteracion": "Efod",
            "significado": "Vestidura sacerdotal.",
            "descripcion": "Prenda relacionada con el servicio sacerdotal y el sumo sacerdote.",
            "aliases": ["Efod"],
        },
        {
            "palabra": "Urim",
            "hebreo": "\u05d0\u05d5\u05e8\u05d9\u05dd",
            "transliteracion": "Urim",
            "significado": "Luces.",
            "descripcion": "Elemento asociado al pectoral sacerdotal para consultar delante de Dios.",
            "aliases": ["Urim"],
        },
        {
            "palabra": "Tumim",
            "hebreo": "\u05ea\u05de\u05d9\u05dd",
            "transliteracion": "Tumim",
            "significado": "Perfecciones o integridades.",
            "descripcion": "Elemento asociado al pectoral sacerdotal junto con Urim.",
            "aliases": ["Tumim", "Thummim"],
        },
        {
            "palabra": "Belen",
            "hebreo": "\u05d1\u05d9\u05ea \u05dc\u05d7\u05dd",
            "transliteracion": "Beit Lejem",
            "significado": "Casa de pan.",
            "descripcion": "Ciudad de David y lugar asociado al nacimiento de Jesus.",
            "aliases": ["Belen", "Belén", "Bethlehem"],
        },
        {
            "palabra": "Betel",
            "hebreo": "\u05d1\u05d9\u05ea \u05d0\u05dc",
            "transliteracion": "Beit-El",
            "significado": "Casa de Dios.",
            "descripcion": "Lugar donde Jacob tuvo la vision de la escalera.",
            "aliases": ["Betel", "Bet-el", "Bethel"],
        },
        {
            "palabra": "Peniel",
            "hebreo": "\u05e4\u05e0\u05d9\u05d0\u05dc",
            "transliteracion": "Peni-El",
            "significado": "Rostro de Dios.",
            "descripcion": "Lugar donde Jacob dijo haber visto a Dios cara a cara.",
            "aliases": ["Peniel", "Penuel"],
        },
        {
            "palabra": "Moriah",
            "hebreo": "\u05de\u05e8\u05d9\u05d4",
            "transliteracion": "Moriah",
            "significado": "Visto/provisto por Jehova.",
            "descripcion": "Monte asociado al sacrificio de Isaac y al templo.",
            "aliases": ["Moriah", "Moria"],
        },
        {
            "palabra": "Horeb",
            "hebreo": "\u05d7\u05e8\u05d1",
            "transliteracion": "Jorev",
            "significado": "Sequedad, desierto.",
            "descripcion": "Monte de Dios, asociado a Moises y la revelacion divina.",
            "aliases": ["Horeb"],
        },
        {
            "palabra": "Sinai",
            "hebreo": "\u05e1\u05d9\u05e0\u05d9",
            "transliteracion": "Sinai",
            "significado": "Monte Sinai.",
            "descripcion": "Monte donde Israel recibio la ley.",
            "aliases": ["Sinai", "Sinaí"],
        },
        {
            "palabra": "Canaan",
            "hebreo": "\u05db\u05e0\u05e2\u05df",
            "transliteracion": "Kena'an",
            "significado": "Humillado, bajo, sometido.",
            "descripcion": "Nombre de la tierra prometida y de sus antiguos habitantes.",
            "aliases": ["Canaan", "Canaán", "Cananeo", "Cananeos"],
        },
        {
            "palabra": "Jerusalen",
            "hebreo": "\u05d9\u05e8\u05d5\u05e9\u05dc\u05dd",
            "transliteracion": "Yerushalayim",
            "significado": "Ciudad/fundamento de paz.",
            "descripcion": "Ciudad santa, centro espiritual e historico de Israel.",
            "aliases": ["Jerusalen", "Jerusalén", "Yerushalayim"],
        },
        {
            "palabra": "Getsemani",
            "hebreo": "\u05d2\u05ea \u05e9\u05de\u05e0\u05d9\u05dd",
            "transliteracion": "Gat Shemanim",
            "significado": "Prensa de aceite.",
            "descripcion": "Lugar donde Jesus oro antes de ser entregado.",
            "aliases": ["Getsemani", "Getsemaní", "Gethsemani"],
        },
        {
            "palabra": "Gehenna",
            "hebreo": "\u05d2\u05d9\u05d0 \u05d1\u05df \u05d4\u05e0\u05dd",
            "transliteracion": "Ge Ben-Hinnom",
            "significado": "Valle del hijo de Hinom.",
            "descripcion": "Lugar usado como imagen de juicio.",
            "aliases": ["Gehenna", "Gehena", "Hinom"],
        },
        {
            "palabra": "Silo",
            "hebreo": "\u05e9\u05d9\u05dc\u05d4",
            "transliteracion": "Shiloh",
            "significado": "Reposo o enviado.",
            "descripcion": "Lugar del tabernaculo; tambien termino mesianico segun algunas lecturas.",
            "aliases": ["Silo", "Shiloh"],
        },
        {
            "palabra": "Siloe",
            "hebreo": "\u05e9\u05dc\u05d5\u05d7",
            "transliteracion": "Shiloaj",
            "significado": "Enviado.",
            "descripcion": "Estanque mencionado en el Evangelio de Juan.",
            "aliases": ["Siloe", "Siloé"],
        },
        {
            "palabra": "Israel",
            "hebreo": "\u05d9\u05e9\u05e8\u05d0\u05dc",
            "transliteracion": "Yisrael",
            "significado": "Dios lucha / Dios prevalece.",
            "descripcion": "Nombre dado a Jacob y luego al pueblo del pacto.",
            "aliases": ["Israel", "Israelita", "Israelitas"],
        },
        {
            "palabra": "Jacob",
            "hebreo": "\u05d9\u05e2\u05e7\u05d1",
            "transliteracion": "Yaakov",
            "significado": "El que toma del talon; suplantador.",
            "descripcion": "Patriarca que recibio el nombre Israel.",
            "aliases": ["Jacob", "Jacobo", "Yaakov"],
        },
        {
            "palabra": "Abraham",
            "hebreo": "\u05d0\u05d1\u05e8\u05d4\u05dd",
            "transliteracion": "Avraham",
            "significado": "Padre de multitud.",
            "descripcion": "Patriarca llamado por Dios y padre del pueblo del pacto.",
            "aliases": ["Abraham", "Abram", "Avraham"],
        },
        {
            "palabra": "Isaac",
            "hebreo": "\u05d9\u05e6\u05d7\u05e7",
            "transliteracion": "Yitzjak",
            "significado": "Risa; el rie.",
            "descripcion": "Hijo de Abraham y Sara.",
            "aliases": ["Isaac", "Yitzjak"],
        },
        {
            "palabra": "Sara",
            "hebreo": "\u05e9\u05e8\u05d4",
            "transliteracion": "Sarah",
            "significado": "Princesa.",
            "descripcion": "Esposa de Abraham y madre de Isaac.",
            "aliases": ["Sara", "Sarai", "Sarah"],
        },
        {
            "palabra": "Moises",
            "hebreo": "\u05de\u05e9\u05d4",
            "transliteracion": "Moshe",
            "significado": "Sacado de las aguas.",
            "descripcion": "Libertador de Israel y mediador de la ley.",
            "aliases": ["Moises", "Moisés", "Moshe"],
        },
        {
            "palabra": "Josue",
            "hebreo": "\u05d9\u05d4\u05d5\u05e9\u05e2",
            "transliteracion": "Yehoshua",
            "significado": "Jehova salva.",
            "descripcion": "Nombre relacionado con Yeshua/Jesus; lider que introdujo a Israel en Canaan.",
            "aliases": ["Josue", "Josué", "Yehoshua"],
        },
        {
            "palabra": "Jesus",
            "hebreo": "\u05d9\u05e9\u05d5\u05e2",
            "transliteracion": "Yeshua",
            "significado": "Salvacion; Jehova salva.",
            "descripcion": "Nombre del Senor Jesucristo en forma hebrea/aramea.",
            "aliases": ["Jesus", "Jesús", "Yeshua"],
        },
        {
            "palabra": "David",
            "hebreo": "\u05d3\u05d5\u05d3",
            "transliteracion": "David",
            "significado": "Amado.",
            "descripcion": "Rey de Israel y autor de muchos salmos.",
            "aliases": ["David"],
        },
        {
            "palabra": "Salomon",
            "hebreo": "\u05e9\u05dc\u05de\u05d4",
            "transliteracion": "Shlomo",
            "significado": "Pacifico; de paz.",
            "descripcion": "Hijo de David, rey asociado a sabiduria y templo.",
            "aliases": ["Salomon", "Salomón", "Shlomo"],
        },
        {
            "palabra": "Samuel",
            "hebreo": "\u05e9\u05de\u05d5\u05d0\u05dc",
            "transliteracion": "Shemuel",
            "significado": "Oido por Dios / nombre de Dios.",
            "descripcion": "Profeta y juez de Israel.",
            "aliases": ["Samuel"],
        },
        {
            "palabra": "Daniel",
            "hebreo": "\u05d3\u05e0\u05d9\u05d0\u05dc",
            "transliteracion": "Daniyyel",
            "significado": "Dios es mi juez.",
            "descripcion": "Profeta llevado a Babilonia.",
            "aliases": ["Daniel"],
        },
        {
            "palabra": "Elias",
            "hebreo": "\u05d0\u05dc\u05d9\u05d4\u05d5",
            "transliteracion": "Eliyahu",
            "significado": "Mi Dios es Jehova.",
            "descripcion": "Profeta del Senor frente a la idolatria de Baal.",
            "aliases": ["Elias", "Elías", "Eliyahu"],
        },
        {
            "palabra": "Eliseo",
            "hebreo": "\u05d0\u05dc\u05d9\u05e9\u05e2",
            "transliteracion": "Elisha",
            "significado": "Dios es salvacion.",
            "descripcion": "Profeta sucesor de Elias.",
            "aliases": ["Eliseo", "Elisha"],
        },
        {
            "palabra": "Isaias",
            "hebreo": "\u05d9\u05e9\u05e2\u05d9\u05d4\u05d5",
            "transliteracion": "Yeshayahu",
            "significado": "Jehova salva.",
            "descripcion": "Profeta mayor con fuerte mensaje mesianico.",
            "aliases": ["Isaias", "Isaías", "Yeshayahu"],
        },
        {
            "palabra": "Jeremias",
            "hebreo": "\u05d9\u05e8\u05de\u05d9\u05d4\u05d5",
            "transliteracion": "Yirmeyahu",
            "significado": "Jehova levanta o establece.",
            "descripcion": "Profeta llamado antes de nacer.",
            "aliases": ["Jeremias", "Jeremías"],
        },
        {
            "palabra": "Ezequiel",
            "hebreo": "\u05d9\u05d7\u05d6\u05e7\u05d0\u05dc",
            "transliteracion": "Yejezkel",
            "significado": "Dios fortalece.",
            "descripcion": "Profeta del exilio.",
            "aliases": ["Ezequiel"],
        },
        {
            "palabra": "Zacarias",
            "hebreo": "\u05d6\u05db\u05e8\u05d9\u05d4",
            "transliteracion": "Zekharyah",
            "significado": "Jehova recuerda.",
            "descripcion": "Nombre profetico y sacerdotal.",
            "aliases": ["Zacarias", "Zacarías"],
        },
        {
            "palabra": "Malaquias",
            "hebreo": "\u05de\u05dc\u05d0\u05db\u05d9",
            "transliteracion": "Malakhi",
            "significado": "Mi mensajero.",
            "descripcion": "Ultimo profeta del Antiguo Testamento en el orden cristiano.",
            "aliases": ["Malaquias", "Malaquías"],
        },
        {
            "palabra": "Juda",
            "hebreo": "\u05d9\u05d4\u05d5\u05d3\u05d4",
            "transliteracion": "Yehudah",
            "significado": "Alabanza.",
            "descripcion": "Tribu de la cual viene David y el Mesias.",
            "aliases": ["Juda", "Judá", "Judas", "Judio", "Judios"],
        },
    ]
)


DICCIONARIO_HEBREO.sort(key=lambda entrada: normalizar_palabra(entrada.get("palabra", "")))

_INDICE = {}
for entrada in DICCIONARIO_HEBREO:
    for alias in entrada.get("aliases", []):
        _INDICE[normalizar_palabra(alias)] = entrada


_PATRON_FRAGMENTOS = re.compile(r"[^\W\d_]+(?:[-'][^\W\d_]+)*|[^\w]+|\d+|_+")


def entradas_diccionario():
    return sorted(
        DICCIONARIO_HEBREO,
        key=lambda entrada: normalizar_palabra(entrada.get("palabra", "")),
    )


def entrada_para_palabra(palabra):
    return _INDICE.get(normalizar_palabra(palabra))


def fragmentos_con_diccionario(texto):
    for coincidencia in _PATRON_FRAGMENTOS.finditer(str(texto or "")):
        fragmento = coincidencia.group(0)
        yield fragmento, entrada_para_palabra(fragmento), coincidencia.start(), coincidencia.end()
